server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

app:
  frontend:
    url: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://16.184.60.125:3306/gradi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


fastApi:
  service:
    url: http://central-01.tcp.tunnel.elice.io:55638

  # kafka:
  #   bootstrap-servers: 16.184.60.125:9092
  #   consumer:
  #     group-id: grading-group
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   listener:
  #     missing-topics-fatal: false


aws:
  s3:
    bucket: gradibucket
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region:
    static: ap-northeast-2  # ?? ?? ??

  sts:
    account-id: 889389777460     # 본인 AWS 계정 ID
    role-name: fastapi-upload-role
    region: ap-northeast-2

